Se arreglo la validacion del campo email para que permita un formato …
Team-6-R-L-Academy-Backend/api-users pull request #10
Opened 2024-06-21 16:59 UTC by tarrillollontopVictor

Se arreglo el campo email con un formato de mail correcto, permitiendo el dominio adecuado como gmail.com, outlook.com o yahoo.com

2024-06-22 14:29 UTC, AntoCant reviewed
En el hilo de discord te dejo el identado que estamos usando.

2024-06-22 14:29 UTC, AntoCant commented on src/main/java/com/demo/apiusers/dtos/request/UserRequestDTO.java
> +           message = "{The email must contain letters at the beginning, @ and a valid domain (gmail.com, outlook.com or yahoo.com)}")
la validación tiene que permitir cualquier formato de mail valido, no solo 3 formatos

2024-06-22 14:29 UTC, AntoCant commented on src/main/java/com/demo/apiusers/model/RlRole.java
> +import jakarta.validation.constraints.Positive;
Borrar import fuera de uso

2024-06-25 21:15 UTC, LeanBaier requested changes

2024-06-25 21:15 UTC, LeanBaier commented on src/main/java/com/demo/apiusers/dtos/request/UserRequestDTO.java
> +   @Pattern(regexp = "^[A-Za-z]+@[A-Za-z]+\\.(edu\\.pe|[A-Za-z]{3})$", message =
Dejar la validación para que después del "." permita entre 2 y 3 caracteres

2024-06-26 21:14 UTC, AntoCant approved these changes

2024-06-28 21:22 UTC, LeanBaier approved these changes

2024-07-01 21:17 UTC, merged