Feature/RLA-4
Team-6-R-L-Academy-Backend/api-users pull request #5
Opened 2024-06-06 03:44 UTC by AntoCant

Se agrega login, la generacion de JWT, validaciones y manejo de errores 

![image](https://github.com/Team-6-R-L-Academy-Backend/api-users/assets/126527251/9b2322a8-daf9-4dee-b2fe-801517ee28c3)

Json de prueba:

{
    "email": "Anto3@gmail.com",
    "password" : "Ac123456*"
}

Cargar rol, user y pass en base de datos para poder hacer las pruebas.

2024-06-06 15:11 UTC, LeanBaier requested changes

2024-06-06 15:11 UTC, LeanBaier commented on src/main/java/com/demo/apiusers/dtos/request/UserRequestDTO.java
> +   private String password;
Quitar anotaciones duplicadas

2024-06-06 15:11 UTC, LeanBaier commented on src/main/java/com/demo/apiusers/handler/ValidationExceptionErrorHandler.java
> +      log.error("Validation error");
logear la exception con el mensaje

2024-06-06 15:11 UTC, LeanBaier commented on src/main/java/com/demo/apiusers/handler/UserNameNotFoundExceptionErrorHandler.java
> +      log.error("non-existent user in the database", e);
El mensaje debe estar relacionado a la exception, no al caso de uso del service o repository

2024-06-06 15:11 UTC, LeanBaier commented on src/main/java/com/demo/apiusers/controller/RlUserController.java
> +public class RlUserController {
Falta anotacion @Validated para que funcionen las validaciones dentro del controller

2024-06-06 15:29 UTC, AntoCant commented on src/main/java/com/demo/apiusers/handler/ValidationExceptionErrorHandler.java
> +      log.error("Validation error");
Osea e.getMessage?

2024-06-06 15:30 UTC, AntoCant commented on src/main/java/com/demo/apiusers/dtos/request/UserRequestDTO.java
> +   private String password;
Dale

2024-06-06 15:31 UTC, AntoCant commented on src/main/java/com/demo/apiusers/handler/UserNameNotFoundExceptionErrorHandler.java
> +      log.error("non-existent user in the database", e);
userName  not found? Con eso estamos ?

2024-06-06 15:32 UTC, AntoCant commented on src/main/java/com/demo/apiusers/controller/RlUserController.java
> +public class RlUserController {
Dale, lo agrego

2024-06-06 18:04 UTC, LeanBaier commented on src/main/java/com/demo/apiusers/handler/ValidationExceptionErrorHandler.java
> +      log.error("Validation error");
con el logger podes pasar directamente la exception
log.error("Validation error", e);

2024-06-06 18:08 UTC, LeanBaier commented on src/main/java/com/demo/apiusers/handler/UserNameNotFoundExceptionErrorHandler.java
> +      log.error("non-existent user in the database", e);
Podria ser, la idea es q el log sea util

2024-06-07 01:23 UTC, AntoCant commented on src/main/java/com/demo/apiusers/handler/ValidationExceptionErrorHandler.java
> +      log.error("Validation error");
listo

2024-06-07 01:23 UTC, AntoCant commented on src/main/java/com/demo/apiusers/handler/UserNameNotFoundExceptionErrorHandler.java
> +      log.error("non-existent user in the database", e);
listo

2024-06-07 01:23 UTC, AntoCant commented on src/main/java/com/demo/apiusers/controller/RlUserController.java
> +public class RlUserController {
listo

2024-06-07 13:04 UTC, marcosbuenocapillera approved these changes

2024-06-07 13:04 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiusers/controller/RlUserController.java
> +public class RlUserController {
Falta agregar  @validated

2024-06-07 18:24 UTC, LeanBaier approved these changes

2024-06-07 18:26 UTC, merged