feature/RLA-18 (Script)
Team-6-R-L-Academy-Backend/api-users pull request #7
Opened 2024-06-08 18:47 UTC by AntoCant

Se agrega nuevo script y se modifica código para probar el correcto funcionamiento

2024-06-08 23:18 UTC, marcosbuenocapillera approved these changes

2024-06-09 02:53 UTC, LeanBaier requested changes

2024-06-09 02:53 UTC, LeanBaier commented on src/main/resources/scripts/createApiusersSchema.sql
> +    user_name VARCHAR(100) NOT NULL,
username debe ser una sola palabra

2024-06-09 05:03 UTC, AntoCant commented on src/main/resources/scripts/createApiusersSchema.sql
> +    user_name VARCHAR(100) NOT NULL,
si mala mia. Listo

2024-06-10 21:03 UTC, LeanBaier approved these changes

2024-06-10 21:14 UTC, merged